### ISSUE TITLE
Still issues with Blank Section & Body + a Functionality Question 

### ISSUE THREAD

**Issue by nickknyc** [bbawj/obsidian-semantic-search#11]
Brendan,

Dug back in today and I was still having issues with blank section and body that get generated into my input files. Not a big deal but thought you may want to check. 

Secondly,
I was able to run 100 batches of about 25 embeddings each. That ran well. When I query things, I get results that are not particularly good at all. It doesn't seem to be able to reason for an answer by looking at data that may only be semantically but not explicitly connected. 

The shot below shows a query.. the results are not at all what I would have expected. Perhaps I do not understand the intentional functionality. What I had expected is that these emberddings would work along with GPT-4 queries and I would get the language capabilities of ChatGPT, but with the additional data from my embeddings... 

Please let me know.

![image](https://github.com/bbawj/obsidian-semantic-search/assets/1598572/0e43c59f-2dda-437b-92f1-6c0ab86083cb)

**Comment by bbawj** [comment]
Hi @nickknyc 

> I was able to run 100 batches of about 25 embeddings each.

If this was able to run, it must mean that there is no row in your generated input file that has both an empty section *and* body, else you would have gotten an API input parameter error as you mentioned in #6. You could have possibly either empty sections *or* body, in which case that could be a result of the section delimiter regular expression which you chose to generate the input with. For e.g. if you chose to match only on headers and your files are formatted such that the headers are separated by a bunch of new lines, the body of such sections would be empty. 

> The shot below shows a query.. the results are not at all what I would have expected. Perhaps I do not understand the intentional functionality. What I had expected is that these emberddings would work along with GPT-4 queries and I would get the language capabilities of ChatGPT, but with the additional data from my embeddings...

This plugin works by finding sections of your input which matches the best semantically to the input query. This works by parsing your note vault into [embeddings](https://platform.openai.com/docs/guides/embeddings), which in turn is used to calculate how similar/related your query is to sections of your notes. The intended outcome of this, is to be able to find and quickly jump to parts of your notes without relying on trying to match specific text which you think may lead you to that part of your notes. This makes it fundamentally different from ChatGPT,

In your example, sections of your notes will be used to find what's most related to the query "what makes a good tool for building a box". The sections of your notes most "related" to that would be the section on "tools/woodworking".

In this case, you might be getting poor results because the structure of your notes and the regular expression you used to delimit your notes do not match well. Fundamentally, if you do not have any sections in your notes that are related to that query. the results will be hot garbage.

**Comment by nickknyc** [comment]
@bbawj thanks so much for all of that explanation. i would strongly suggest putting much of it into the readme. md

to start, the input file already had all rows with missing subject and/or body removed. i had been getting input errors before modification. i used gpt4/code interpreter to find and eliminate the rows.

the regex... I'm really unclear on how to make that help me. I'm new to the embeddings scene 🙃.

the goal of the plugin - finding stuff - ahhh i was not aware of that and then yes it is doing what is intended. I will check out chat-md for a more chat gpt like experience.

and yes, my notes are highly unstructured.. so hot garbage in... hot garbage out🤣

thanks so kuch for taking the time to set me straight!
